#!/bin/env bash

## Copyright (C) 2020-2023 Aditya Shakya <adi1090x@gmail.com>

# Import Current Theme
DIR="$HOME/.config"
STYLE="default"
RASI="~/.config/rofi/scripts/powermenu.rasi"
CNFR="~/.config/rofi/scripts/confirm.rasi"

# Theme Elements
prompt="$(hostname) ($(echo $DESKTOP_SESSION))"
mesg="Uptime: $(uptime -p | sed -e 's/up //g')"

# Options
layout=$(grep 'USE_ICON' "$RASI" | cut -d'=' -f2)
if [[ "$layout" == 'NO' ]]; then
	option_1=" Lock"
	option_2=" Logout"
	option_3=" Suspend"
	option_4=" Hibernate"
	option_5=" Reboot"
	option_6=" Shutdown"
else
	option_1=""
	option_2=""
	option_3=""
	option_4=""
	option_5=""
	option_6=""
fi

cnflayout=$(grep 'USE_ICON' "$CNFR" | cut -d'=' -f2)
if [[ "$cnflayout" == 'NO' ]]; then
	yes=' Yes'
	no=' No'
else
	yes=''
	no=''
fi

# Rofi CMD
rofi_cmd() {
	rofi -dmenu \
		-p "$prompt" \
		-mesg "$mesg" \
		-markup-rows \
		-theme "$RASI"
}

# Pass variables to rofi dmenu
run_rofi() {
	echo -e "$option_1\n$option_2\n$option_3\n$option_4\n$option_5\n$option_6" | rofi_cmd
}

# Confirmation CMD
confirm_cmd() {
	rofi -dmenu \
		-p 'Confirmation' \
		-mesg 'Are you sure?' \
		-theme "$CNFR"
}

# Ask for confirmation
confirm_exit() {
	echo -e "$yes\n$no" | confirm_cmd
}

# Confirm and execute
confirm_run() {	
	selected="$(confirm_exit)"
	if [[ "$selected" == "$yes" ]]; then
        eval "$1" && eval "$2" && eval "$3"
    else
        exit
    fi	
}

# Execute Command
run_cmd() {
	case "$1" in
		'--opt1') betterlockscreen --lock ;;
		'--opt2') confirm_run 'bspc quit' ;;
		'--opt3') confirm_run 'mpc -q pause' 'pulsemixer --mute' 'betterlockscreen --suspend' ;;
		'--opt4') confirm_run 'systemctl hibernate' ;;
		'--opt5') confirm_run 'systemctl reboot' ;;
		'--opt6') confirm_run 'systemctl poweroff' ;;
	esac
}

# Actions
chosen="$(run_rofi)"
case "$chosen" in
    "$option_1") run_cmd --opt1 ;;
    "$option_2") run_cmd --opt2 ;;
    "$option_3") run_cmd --opt3 ;;
    "$option_4") run_cmd --opt4 ;;
    "$option_5") run_cmd --opt5 ;;
    "$option_6") run_cmd --opt6 ;;
esac

